services:
    vroom:
        build: ./vroom
        environment:
         - VIRTUAL_ROOM_SERVER_ADDRESS=vroom_server
         - VIRTUAL_ROOM_SERVER_PORT=65432
         - PYTHONUNBUFFERED=1

        depends_on:
         - vroom_server


    vroom_server:
       build: ./vroom_server
       container_name: vroom_server
       environment:
         - VIRTUAL_ROOM_SERVER_PORT=65432
         - PYTHONUNBUFFERED=1