version: '2'
services:
  mqtt1:
    build: ./mqtt1
    ports:
      - "1883:1883"
    volumes:
      - "./mqtt1/app/mosquitto.conf:/etc/mosquitto/mosquitto.conf"


  message_router:
    build: ./message_router
    environment:
      - MQTT_SERVER_ADDRESS=34.159.168.7
      - MQTT_SERVER_PORT=1883
      - API_SERVER_ADDRESS=data_ingestion_microservice
      - API_SERVER_PORT=5000
      - PYTHONUNBUFFERED=1

    volumes:
      - "./message_router/app:/etc/usr/src/app"

  mariaDB:
    image: 'mariadb:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=dso_db_root_password

  data_ingestion_microservice:
    build: ./data_ingestion_microservice
    ports:
      - '5000:5000'
    links:
      - "mariaDB:mariaDB"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DB_HOST=mariaDB
      - DB_USER=dso_db_user
      - DB_PASSWORD=dso_db_password
      - DB_NAME=dso_db
    depends_on:
      - mariaDB
    volumes:
      - "./data_ingestion_microservice/app:/etc/usr/src/app"



