version: '2'
services:
  mqtt1:
    build: ./mqtt1
    ports:
      - "1883:1883"
    volumes:
      - "./mqtt1/app/mosquitto.conf:/etc/mosquitto/mosquitto.conf"
    
  mqtt2:
    build: ./mqtt2
    ports:
      - "1884:1883"
    volumes:
      - "./mqtt1/app/mosquitto.conf:/etc/mosquitto/mosquitto.conf"


  message_router:
    build: ./message_router
    environment:
      - MQTT_SERVER_ADDRESS=34.159.168.7
      - MQTT_SERVER_PORT=1883
      - MQTT_PORT=1883
      - DATA_INGESTION_API_HOST=data_ingestion_microservice
      - DATA_INGESTION_API_PORT=5000
      - API_SERVER_ADDRESS=data_ingestion_microservice
      - API_HOST=0.0.0.0
      - API_PORT=5000
      - API_SERVER_PORT=5000
      - PYTHONUNBUFFERED= 1

    volumes:
      - "./message_router/app:/etc/usr/src/app"

  mariaDB:
    image: 'mariadb:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=dso_db_root_password

  data_ingestion_microservice:
    build: ./data_ingestion_microservice
    ports:
      - '5000:5000'
    links:
      - "mariaDB:mariaDB"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DB_HOST=mariaDB
      - DB_USER=dso_db_user
      - DB_PASSWORD=dso_db_password
      - DB_NAME=dso_db
    depends_on:
      - mariaDB
    volumes:
      - "./data_ingestion_microservice/app:/etc/usr/src/app"

  frontend:
    build: ./frontend
    ports: 
      - '80:80'
    volumes: 
      - ./frontend/app:/usr/local/apache2/htdocs

  webapp_backend: 
    build: ./webapp_backend
    ports: 
      - '5001:5000'
    environment: 
      - HOST=0.0.0.0
      - PORT=5000
      - DATA_INGESTION_API_ADDRESS=data_ingestion_microservice
      - DATA_INGESTION_API_PORT=5000
      - MESSAGE_ROUTER_API_ADDRESS=message_router
      - MESSAGE_ROUTER_API_PORT=5002
    volumes: 
      - ./webapp_backend/app:/etc/usr/src/app



